# Generated by Django 5.2.5 on 2025-08-25 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_addresstype_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Snapshots',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('move_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_moves', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_moves', to='inventory.location')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('move_type', 'OUTBOUND'), _negated=True), ('from_location__isnull', False), _connector='OR'), name='outbound_requires_from'), models.CheckConstraint(condition=models.Q(models.Q(('move_type', 'TRANSFER'), _negated=True), models.Q(('from_location__isnull', False), ('to_location__isnull', False), models.Q(('from_location', models.F('to_location')), _negated=True)), _connector='OR'), name='transfer_requires_both')],
            },
        ),
    ]
